# Basic Site Settings
locale                  : "en-US"
site_theme              : "default"
title                   : "José Miguel Santos Terán"
title_separator          : "-"
name                     : &name "José Miguel Santos Terán"
description              : &description "Mechatronics Engineer and Teaching Technician specializing in Swarm Robotics and Control Systems."
url                      : "https://jmsantost.github.io" 
baseurl                  : "" 
repository               : "jmsantost/jmsantost.github.io"

# Site Author
author:
  # Biographic information
  avatar           : "profile.png" # Asegúrate de subir una foto con este nombre a /images/
  name             : "José Miguel Santos Terán"
  pronouns         : "he/him"
  bio              : "Mechatronics Engineer | Teaching Technician at UPS | Swarm Robotics Researcher | Former AIROS Club President."
  location         : "Guayaquil, Ecuador"
  employer         : "Universidad Politécnica Salesiana (UPS)"
  uri              : 
  email            : # Puedes poner tu correo institucional o personal aquí

  # Academic websites
  googlescholar    : # Si tienes perfil, pega el URL aquí
  orcid            : # Si tienes ORCID, pega el URL aquí
  researchgate     : 

  # Repositories and software development
  github            : "jmsantost"
  stackoverflow     : 

  # Social media
  linkedin         : "jose-miguel-santos-teran" # Verifica que este sea tu slug de LinkedIn
  twitter          : 
  youtube          :
